# Generated by Django 2.2.4 on 2019-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=250)),
                ('first', models.CharField(max_length=250)),
                ('middle', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250, unique=True)),
                ('most_likely_org', models.CharField(max_length=250)),
                ('positions', models.TextField()),
                ('aliases', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au', models.CharField(blank=True, max_length=250)),
                ('au_org', models.CharField(blank=True, max_length=250)),
                ('au_person', models.CharField(blank=True, max_length=250)),
                ('cc', models.CharField(blank=True, max_length=250)),
                ('cc_org', models.CharField(blank=True, max_length=250)),
                ('collection', models.CharField(blank=True, max_length=250)),
                ('date', models.CharField(blank=True, max_length=250)),
                ('doc_type', models.CharField(blank=True, max_length=250)),
                ('pages', models.IntegerField(blank=True)),
                ('rc', models.CharField(blank=True, max_length=250)),
                ('rc_org', models.CharField(blank=True, max_length=250)),
                ('rc_person', models.CharField(blank=True, max_length=250)),
                ('text', models.TextField(blank=True)),
                ('tid', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('authors', models.ManyToManyField(related_name='document_by_authors', to='main.DjangoPerson')),
                ('recipients', models.ManyToManyField(related_name='document_by_recipients', to='main.DjangoPerson')),
            ],
        ),
    ]
