# Generated by Django 2.2.4 on 2019-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au', models.CharField(blank=True, max_length=250)),
                ('au_org', models.CharField(blank=True, max_length=250)),
                ('au_person', models.CharField(blank=True, max_length=250)),
                ('cc', models.CharField(blank=True, max_length=250)),
                ('cc_org', models.CharField(blank=True, max_length=250)),
                ('collection', models.CharField(blank=True, max_length=250)),
                ('date', models.CharField(blank=True, max_length=250)),
                ('doc_type', models.CharField(blank=True, max_length=250)),
                ('pages', models.IntegerField(blank=True)),
                ('rc', models.CharField(blank=True, max_length=250)),
                ('rc_org', models.CharField(blank=True, max_length=250)),
                ('rc_person', models.CharField(blank=True, max_length=250)),
                ('text', models.TextField(blank=True)),
                ('tid', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
