# Generated by Django 2.2.4 on 2019-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(max_length=255)),
                ('first', models.CharField(max_length=255)),
                ('middle', models.CharField(max_length=255)),
                ('most_likely_org', models.CharField(max_length=250)),
                ('positions', models.TextField()),
                ('aliases', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(to='main.Person'),
        ),
    ]
