# Generated by Django 2.2.4 on 2019-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191114_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
