# Generated by Django 2.2.4 on 2019-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191112_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoperson',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
