# Generated by Django 2.2.4 on 2019-11-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_djangoperson_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoperson',
            name='full_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
