# Generated by Django 2.2.4 on 2019-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191117_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoperson',
            name='first',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='djangoperson',
            name='full_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='djangoperson',
            name='last',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='djangoperson',
            name='middle',
            field=models.CharField(max_length=250),
        ),
    ]
